export const GET_CHAT_DETAILS = "GET_CHAT_DETAILS";
export const SET_CHAT_DETAILS = "SET_CHAT_DETAILS";
export const SET_MESSAGE_CHAT_DETAILS = "SET_MESSAGE_CHAT_DETAILS";
export const GET_FILTERED_RESULT = "GET_FILTERED_RESULT";
export const GET_ALL_RESULT = "GET_ALL_RESULT";
export const SHOW_MESSAGES = "SHOW_MESSAGES";
export const ADD_MESSAGE = "ADD_MESSAGE";

